Hw02 unpack string
alex0206/otus pull request #2
Opened 2020-03-13 09:14 UTC by alex0206

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-03-13 16:54 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/87248/6026/

Здравствуйте!

Спасибо за работу. 
Давайте попробуем добавить новых тестов (негативных и позитивных) и проверить, пройдет ли их ваш код :)

2020-03-13 16:54 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			input:    "2d3",
Маловато вы добавили тестов :)
И необязательно же они должны быть негативные

2020-03-13 16:54 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	if str == "" {
Как считаете, без этой проверки функция будет работать?
И сильно ли вы потеряете в производительности

2020-03-13 16:54 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	symbolCnt := make(map[rune]int)
На больших строках память будет выжирать(
И нужен ли здесь словарь? Вы же всегда работаете с текущим символом

2020-03-13 16:54 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +		symbolCnt[symbol]++
Тест вида
```
input:    "aaabbbccccdddd"
expected: "aaabbbccccdddd"
```
должен не пройти
:)

2020-03-13 18:09 UTC, alex0206 commented on hw02_unpack_string/unpack.go
> +		symbolCnt[symbol]++
Я этот кейс "aaa10b" => "" (некорректная строка) значит неправильно понял. Я подумал, что здесь проблема в том, что строка уже распакована раз идет "aaa". Проблема значит в числе. Про числа я подумал, что именно, когда они в таком виде идут "45" => "" (некорректная строка) тогда проблема.

2020-03-14 15:49 UTC, Antonboom approved these changes
Замечательно!

Такого компактного решения давно я не видел.
10 / 10

2020-03-14 15:49 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +			builder.WriteString(strings.Repeat(string(lastRune), repeatNumber))
Или
```golang
builder.WriteString(strings.Repeat(string(lastRune), repeatNumber - 1))
```

2020-03-14 17:26 UTC, alex0206 commented on hw02_unpack_string/unpack.go
> +			builder.WriteString(strings.Repeat(string(lastRune), repeatNumber))
Было так изначально, но линтер ругается на 1, как магическое число, и чтобы избавиться, пришлось так записать repeatNumber--

2020-03-14 19:41 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +			builder.WriteString(strings.Repeat(string(lastRune), repeatNumber))
```
//nolint:<имя_линтера>
```

2020-03-15 17:19 UTC, alex0206 commented on hw02_unpack_string/unpack.go
> +			builder.WriteString(strings.Repeat(string(lastRune), repeatNumber))
Что-то он не выключается https://i.imgur.com/yhrxb4q.png

2020-03-16 05:04 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +			builder.WriteString(strings.Repeat(string(lastRune), repeatNumber))
Комментарий действует на конкретную строку, не на файл

Т.е. рядом с вашей проблемной строкой его стоит продублировать, на скриншоте `gomnd` задизейблился для `package hw02_unpack_string`

2020-03-17 03:58 UTC, alex0206 commented on hw02_unpack_string/unpack.go
> +			builder.WriteString(strings.Repeat(string(lastRune), repeatNumber))
Да. Работает так. Спасибо.

2020-03-17 03:59 UTC, merged